---

- name: copying filebeat deb file
  copy:
    src: "{{ repo_path }}/{{ filebeat_package }}"
    dest: /root

- name: install a .deb package
  apt:
    deb: /root/{{ filebeat_package }}

# - name: comment out elasticsearch host
#   lineinfile:
#       dest: /etc/filebeat/filebeat.yml
#       regexp: "^output.elasticsearch:"
#       line: "#output.elasticsearch:"    
      
# - name: comment out output.elasticsearch
#   replace:
#       path: /etc/filebeat/filebeat.yml
#       regexp: '(.*localhost:9200.*)'
#       replace: '#\1'          

- name: copy filebeat config file
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    
- name: adding lines in filebeat.yml
  blockinfile:
    path: /etc/filebeat/filebeat.yml
    insertafter: "filebeat.inputs:"
    block: |    
      - type: log
        paths:
          - /var/log/nginx/*.log
        exclude_files: ['\.gz$']
        enabled: true

      output.logstash:
        hosts: ["{{ groups['observer'][0] }}:5400"]

- name: start service filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes

