---

- name: copying filebeat deb file
  copy:
    src: "{{ repo_path }}/{{ filebeat_package }}"
    dest: /root

- name: install a .deb package
  apt:
    deb: /root/{{ filebeat_package }}

- name: start service filebeat
  systemd:
    name: filebeat
    state: started
    enabled: yes

