---

- name: copying filebeat deb file
  copy:
    src: "{{ repo_path }}/{{ filebeat_package }}"
    dest: /root

- name: install a .deb package
  apt:
    deb: /root/{{ filebeat_package }}
    
- name: adding lines in filebeat.yml
  blockinfile:
    path: /etc/filebeat/filebeat.yml
    insertafter: "filebeat.inputs:"
    block: |    
      - type: log
        paths:
          - /var/log/nginx/*.log
        exclude_files: ['\.gz$']
        enabled: true

      output.logstash:
        hosts: ["{{ hostvars[observer]['hostname'] }}:5400"]

- name: comment out output.elasticsearch
  lineinfile:
      dest: /etc/filebeat/filebeat.yml
      regexp: "^output.elasticsearch:"
      line: "#output.elasticsearch:"    
      
- name: comment out output.elasticsearch
  lineinfile:
      dest: /etc/filebeat/filebeat.yml
      regexp: '^hosts: ["localhost:9200"]'
      line: '#hosts: ["localhost:9200"]'          

- name: start service filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes

