---
- name: copying logstash deb file
  copy:
    src: "{{ repo_path }}/{{ logstash_package }}"
    dest: /root

- name: install a .deb package
  ansible.builtin.apt:
    deb: /root/{{ logstash_package }}

- name: copy preconfigured nginx configfile
  copy:
    src: logstash-nginx-es.conf
    dest: /etc/logstash/conf.d

- name: adding lines in logstash.yml
  blockinfile:
    path: /etc/logstash/logstash.yml
    block: |
      path.data: /var/lib/logstash
      path.config: /etc/logstash/conf.d
      path.logs: /var/log/logstash

- name: start service logstash 
  systemd:
    name: logstash 
    state: restarted
    enabled: yes
