---
- name: copying filebeat deb file
  copy:
    src: "{{ repo_path }}/{{ logstash_package }}"
    dest: /root

- name: install a .deb package
  ansible.builtin.apt:
    deb: /root/{{ logstash_package }}

# HERE CONFIG

- name: start service logstash 
  systemd:
    name: logstash 
    state: started
    enabled: yes
