---
#
# Playbook to install the ELK stack + Beats
#
- hosts: observer
  become: true
  roles:
  - { role: elasticsearch }
#  - { role: logstash }
#  - { role: kibana }

- hosts: observer, nginx
  become: true
  roles:
  - { role: filebeat }
