---
#
# Playbook to install the ELK stack + Beats
#
- hosts: observer
  become: true
  roles:
  - role: elasticsearch
  - role: logstash
  - role: kibana

- hosts: www
  become: true
  roles:
  - role: filebeat
