- name: install grafana
  hosts: observer
  become: true
  #vars:
    # repo_path: "/root/ladmex"  
    # prometheus_user: promuser
    # db_server_ip: "{{ hostvars[groups['mysql_master'][0]].inventory_hostname }}"
    # prometh_gz_url: "https://github.com/prometheus/prometheus/releases/download/v2.37.5/prometheus-2.37.5.linux-amd64.tar.gz"
  
  tasks:
  - name: copying key file
    copy:
      src: /root/ladmex/grafana.key
      dest: /usr/share/keyrings/

  # - name: install gpg++
  #   apt:
  #     name: gnupg, software-properties-common, apt-transport-https
  #     state: present
  #     update_cache: yes

  # - name: add gpg hey
  #   apt_key:
  #     url: "https://apt.grafana.com/gpg.key"
  #     validate_certs: no

  - name: add repository
    apt_repository:
      repo: "deb https://apt.grafana.com stable main"             
      state: present
      validate_certs: no

  - name: install grafana
    apt:
      name: grafana
      state: latest
      update_cache: yes

  - name: start service grafana-server
    systemd:
      name: grafana-server
      state: started
      enabled: yes

  - name: wait for service up
    uri:
      url: "http://127.0.0.1:3000"
      status_code: 200
    register: __result
    until: __result.status == 200
    retries: 120
    delay: 1

  # - name: change admin password for grafana gui
  #   shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  #   register: __command_admin
  #   changed_when: __command_admin.rc !=0