- name: install grafana
  hosts: observer
  become: true
  vars:
    repo_path: "/root/ladmex"  
    # prometheus_user: promuser
    # db_server_ip: "{{ hostvars[groups['mysql_master'][0]].inventory_hostname }}"
    grafana_package: "grafana_9.3.2_amd64.deb"
  
  tasks:
  - name: copying grafana deb file
    copy:
      src: "{{ repo_path }}/{{ grafana_package }}"
      dest: /root

  - name: install a .deb package
    ansible.builtin.apt:
      deb: /root/{{ grafana_package }}

  # - name: add repository
  #   apt_repository:
  #     repo: "deb https://apt.grafana.com stable main"             
  #     state: present
  #     validate_certs: no

  # - name: install grafana
  #   apt:
  #     name: grafana
  #     state: latest
  #     update_cache: yes

  - name: start service grafana-server
    systemd:
      name: grafana-server
      state: started
      enabled: yes

  - name: wait for service up
    uri:
      url: "http://127.0.0.1:3000"
      status_code: 200
    register: __result
    until: __result.status == 200
    retries: 120
    delay: 1

  # - name: change admin password for grafana gui
  #   shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  #   register: __command_admin
  #   changed_when: __command_admin.rc !=0