---
- name: install mediawiki, copy config and configure
  hosts: mediawikis
  become: true
  vars:
    nginx_name: "{{ hostvars[groups['www'][0]].ansible_hostname }}"
    db_server_ip: "{{ hostvars[groups['mysql_master'][0]].inventory_hostname }}"
  tasks:

  - name: install mediawiki & others
    apt: 
      state: present 
      update_cache: yes
      name:       
        - apache2
        - php
        - php-mysql
        - libapache2-mod-php
        - php-xml
        - php-mbstring
        - mediawiki

  - name: copying mediawiki config file from repo to /etc/mediawiki
    copy:
      src: /root/ladmex/LocalSettings.php
      dest: /etc/mediawiki/

  - name: modifying LocalSettings.php     
    lineinfile:
      dest: /etc/mediawiki/LocalSettings.php
      regexp: '^\$wgServer'    
      line: '$wgServer = "http://{{ nginx_name }}.i-tango.ru";'            

  - name: modifying LocalSettings.php mysql host    
    lineinfile:
      dest: /etc/mediawiki/LocalSettings.php
      regexp: '^\$wgDBserver'
      line: '$wgDBServer = "{{ db_server_ip }}";'     
    notify: 
       - restart apache2

  - name: Run update.php script after restore mediawiki
    shell: php /var/lib/mediawiki/maintenance/update.php --quick
    ignore_errors: true
    no_log: true

  handlers: 
  - name: restart apache2
    service: 
      name: apache2
      state: restarted
