---
- name: install mediawiki, copy config and configure
  hosts: mediawiki2
  become: true
  vars:
    nginx_name: "{{ hostvars[groups['www'][0]].ansible_hostname }}"
    db_server_ip: "{{ hostvars[groups['mysql_master'][0]].inventory_hostname }}"
    mediawiki_gz_url: "https://releases.wikimedia.org/mediawiki/1.39/mediawiki-1.39.0.tar.gz"
  tasks:

  - name: install mediawiki & others
    apt: 
      state: present 
      update_cache: yes
      name:       
        - apache2
        - php
        - php-mysql
        - php-json
        - libapache2-mod-php
        - php-xml
        - php-mbstring
        - php-curl 
        - php-intl
        - php-gd
        - mariadb-server
        - texlive
        - imagemagick
        - unzip

  - name: create dir mediawiki
    file:
      path: /var/www/html/mediawiki/
      state: present
  
  - name: download and unpack mediawiki
    unarchive:
      src: "{{ mediawiki_gz_url }}"
      dest: /var/www/html/mediawiki
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: copying mediawiki config file from repo to /etc/mediawiki
    copy:
      src: /root/ladmex/LocalSettings.php
      dest: /var/www/html/mediawiki/

  - name: modifying LocalSettings.php     
    lineinfile:
      dest: /var/www/html/mediawiki/LocalSettings.php
      regexp: '^\$wgServer'    
      line: '$wgServer = "http://{{ nginx_name }}.i-tango.ru";'            

  - name: modifying LocalSettings.php mysql host    
    lineinfile:
      dest: /var/www/html/mediawiki/LocalSettings.php
      regexp: '^\$wgDBserver'
      line: '$wgDBServer = "{{ db_server_ip }}";'     
    notify: 
       - restart apache2

  # - name: Run update.php script after restore mediawiki
  #   shell: php /var/lib/mediawiki/maintenance/update.php --quick
  #   ignore_errors: true

  handlers: 
  - name: restart apache2
    service: 
      name: apache2
      state: restarted
