---
- name: install nginx, copy nginx config
  hosts: mediawikis
  become: true

  tasks:

  - name: install mediawiki & others
    apt: 
      state: present 
      update_cache: yes
      name:       
        - apache2
        - php
        - php-mysql
        - libapache2-mod-php
        - php-xml
        - php-mbstring
        - mediawiki

  - name: copying mediawiki config file from repo to /etc/mediawiki
    copy:
      src: /root/ladmex/LocalSettings.php
      dest: /etc/mediawiki/

  - name: modifying LocalSettings.php     
    lineinfile:
      dest: /etc/mediawiki/LocalSettings.php
      regexp: '^$wgServer = '
      line: '$wgServer = "http://nginx-a.i-tango.ru";'      
    notify: 
       - restart apache2

  handlers: 
  - name: restart apache2
    service: 
      name: apache2
      state: restarted
