---
- name: install maria-db server, copy cnfig
  # hosts: mysql_master
  hosts: mysql
  become: true

  tasks:

  - name: install mariadb-server
    apt: 
      name: mariadb-server
      state: present 

  - name: install python3-pymysql
    apt: 
      name: python3-pymysql
      state: present 

  - name: remove default config from mariadb.conf.d
    file:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      state: absent

  - name: remove default config from etc/mysql      
    file:
      path: /etc/mysql/my.conf
      state: absent

  - name: copying maria-db config file from repo to mariadb.conf.d
    copy:
      src: /root/ladmex/50-server.cnf
      dest: /etc/mysql/mariadb.conf.d/

  - name: copying maria-db config file from repo to etc/mysql
    copy:
      src: /root/ladmex/my.cnf
      dest: /etc/mysql/
    notify: 
      - restart mariadb-server

  - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in db1 and db2
    mysql_user:
      # login_host: 'localhost'
      # login_user: 'root'
      # login_password: ''
      name: root
      password: MW@2022!
      host: localhost
      login_unix_socket: /run/mysqld/mysqld.sock
      #priv: '*.*:ALL,GRANT'
      state: present

  - name: copying maria-db creds file .my.cnf from admin host to mysql_host
    copy:
      src: /root/.my.cnf
      dest: /root/

  - name: creating database my_wiki
    mysql_db:
      name: my_wiki
      state: present

  - name: copying wiki db backup folder to mysql_host
    copy:
      src: /root/ladmex/backup
      dest: /root/

  - name: restoring database from backup
    mysql_db:
      name: my_wiki
      state: import
      target: /root/backup/my_wiki/*
      #my_wiki.actor.gz

  handlers: 
  - name: restart mariadb-server
    service: 
      name: mariadb
      state: restarted