---
- name: install git and nginx, copy nginx config
  hosts: nginx
  become: true

  tasks:
  # - name: install git
  #   apt:
  #     name: git
  #     state: present
  #     update_cache: yes

  # - name: Clone a repo from github
  #   git:
  #     repo: https://github.com/tovmayor/ladmex.git
  #     dest: /root/ladmex

  - name: install nginx
    apt: 
      name: nginx 
      state: present 

  - name: enable on boot
    service: 
      name: nginx 
      state: started 
      enabled: yes
 
  - name: copying nginx proxy config file from repo to sites-enabled
    file:
      path: /etc/nginx/sites-enabled/*
      state: absent

  - name: copying nginx proxy config file from repo to sites-enabled
    copy:
      src: /root/ladmex/nginx_upstream.conf
      dest: /etc/nginx/sites-enabled/
    notify: 
       - restart nginx

  handlers: 
  - name: restart nginx
    service: 
      name: nginx
      state: restarted
