---
- name: install nginx, copy nginx config
  hosts: nginx
  become: true

  tasks:

  - name: install nginx
    apt: 
      name: nginx 
      state: present 

  - name: enable on boot
    service: 
      name: nginx 
      state: started 
      enabled: yes
 
  - name: remove default config from sites-enabled
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: copying nginx proxy config file from repo to sites-enabled
    copy:
      src: /root/ladmex/nginx_upstream.conf
      dest: /etc/nginx/sites-enabled/
    notify: 
       - restart nginx

  handlers: 
  - name: restart nginx
    service: 
      name: nginx
      state: restarted
