---

- name: create VM on Proxmox host
  hosts: vmpool01
  become: true
  gather_facts: no

  vars:
    api_host_name: vmpool01.i-tango.ru
    api_user_name: root@pam
    api_pass: kesomago
    node_name: vmpool01
    vm_template: ubuntu2004-cloud-templ
    templ_id: 210

    vm_new_id: 136
    vm_new_name: test1
    storage_name: SSD
    sock: 1
    core: 2
    mem: 2048
    disk_size: 7G
    net_value: 'virtio,bridge=vmbr1'
    gw_value: 192.168.82.1
    ip_value: 192.168.82.60
    nameservers: 192.168.82.2 192.168.82.3
    domain: i-tango.ru

  tasks:

  - name: create a full clone of the templ with id 210
    community.general.proxmox_kvm:
      # api_token_id: "root@pam!terraform"  
      # api_token_secret: "dfb7917c-3f39-49c5-8428-6cf0d715fb38"

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      clone: "{{ vm_template }}"
      vmid: "{{ templ_id }}"
      full: yes
      newid: "{{ vm_new_id  }}"
      name: "{{ vm_new_name }}"
      storage: "{{ storage_name }}"
      format: raw
#      timeout: 200

  - name: update VM's cpu/memory
    community.general.proxmox_kvm:

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      update: yes

      vmid: "{{ vm_new_id }}"
      sockets: "{{ sock }}"
      cores: "{{ core }}"
      memory: "{{ mem }}"

  - name: setting disk size
    shell:
      cmd: qm resize {{ vm_new_id  }} scsi0 {{ disk_size }}

  - name: setting network
    shell: qm set {{ vm_new_id }} -net0 {{ net_value }} -ipconfig0 'gw={{ gw_value }},ip={{ ip_value }}/24' -nameserver '{{ nameservers }}' -searchdomain {{ domain }}

  - name: starting VM 
    community.general.proxmox_kvm:

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      vmid: "{{ vm_new_id }}"
      state: started

#  - name: adding newly created VM to ansible's inventory
#    add_host:
#      name: "{{ vm_new_name }}"
#      hostname: "{{ ip_value }}"
