---

# create vm

- name: create VM on Proxmox host
  hosts: vmpool01
  become: true
  # vars:
  #   local_repo: '/root/ladmex'

  tasks:

  - name: Create a full clone of the templ with id 100
    community.general.proxmox:
      vmid: 135
      node: "vmpool01"
      api_user: "root@pam"
      api_password: "kesomago"
      # api_token_id: "root@pam!terraform"  
      # api_token_secret: "dfb7917c-3f39-49c5-8428-6cf0d715fb38"
      api_host: "https://192.168.80.10:8006/api2/json"
      clone: 210
      clone_type: full
      hostname: "passbolt"
      storage: "SSD"
      cpus: 1
      cores: 2
      disk: "10G"
      ip_address: "192.168.82.31/24" 
      memory: 4096
      pubkey: "/root/.ssh/id_rsa.pub"
