---

- name: create VM on Proxmox host
  hosts: vmpool01
  become: true
  gather_facts: no

  vars:
#   PVE connestion and template parameters
    api_host_name: vmpool01.i-tango.ru
    api_user_name: root@pam
    node_name: vmpool01
    vm_template: ubuntu2004-cloud
    templ_id: 211
#   new VM's common parameters
    storage_name: SSD
    net_value: 'virtio,bridge=vmbr1'
    gw_value: 192.168.82.1
    nameservers: 192.168.82.2 192.168.82.3
    domain: i-tango.ru
    ssh_pub: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+BK8ZYvPaZ0VighkzODkJWpFaGGlcInIiX19xrFU/fH85LZ0B3z79z1lSRdu+cVtV98TakYpMD6rm01N8f0FpKVMOJLTqyx/VaSC2Dse1fo3qISAB5b6jpkKc9GjHBtfHGsG4i/qinakrmKgpt1AhVhX+nYhvNWLMZxVLs9UHnoN2vXtFo9wCGMh7AxMu2oTqi8zk5Fip/DrRvXBN3zBBhVfWMXUta1mTbsquirVZUdTV70vlhg7aabV7aFyN3YASrHJutIl/BC3BaPwoJAAba5YS2WIrMbp3MYcwVHsSBB0EEj39xEgZj2Se3d9Hb9t+zOShdQGVmThsdnnTSkDefmiMIFugYJDX742+Uy7m80CyJ6gm4TlYV0CKl3qqPlvwuRRwUYM8O7BFFuGKVu+sQsRdcrF0kCi+cspQUAzIWcxTfgmDkxqMjRa8GkV95hLJaTuJWBYsr1NEaPCcc2NbhThxfVd9hYIXTw+fLQlP4hJK8hFtp+OSU3WWMP05Y9E= i-tango\andrey_abramenko@DESKTOP-CQLGVSH'
#   new VM's unique parameters
    vms:
      vm1:
        vm_new_id: 138
        vm_new_name: test-1      # VM name must DO NOT contain '_'
        sock: 1
        core: 2
        mem: 2048
        disk_size: 6G
        ip_value: 192.168.82.62

      vm2:
        vm_new_id: 139
        vm_new_name: test-2      # VM name must DO NOT contain '_'
        sock: 1
        core: 2
        mem: 2048
        disk_size: 6G
        ip_value: 192.168.82.63

  vars_prompt:
    - name: api_pass
      prompt: Enter password to PVE {{ api_user_name }} account

  tasks:

  - name: create a full clone of the templ with id {{ templ_id }}
    community.general.proxmox_kvm:
      # api_token_id: "root@pam!terraform"
      # api_token_secret: "dfb7917c-3f39-49c5-8428-6cf0d715fb38"

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      clone: "{{ vm_template }}"
      vmid: "{{ templ_id }}"
      full: yes
      newid: "{{ item.value.vm_new_id  }}"
      name: "{{ item.value.vm_new_name }}"
      storage: "{{ storage_name }}"
      format: raw
    loop: "{{ lookup('dict', vms) }}"  

  - name: update VM's cpu/memory 
    community.general.proxmox_kvm:
      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      update: yes
      vmid: "{{ item.value.vm_new_id }}"
      sockets: "{{ item.value.sock }}"
      cores: "{{ item.value.core }}"
      memory: "{{ item.value.mem }}"
    loop: "{{ lookup('dict', vms) }}"

  - name: setting disk size 
    shell: qm resize {{ item.value.vm_new_id  }} scsi0 {{ item.value.disk_size }}
    loop: "{{ lookup('dict', vms) }}"  

  - name: setting network with addr {{ ip_value }}/24
    shell: qm set {{ item.value.vm_new_id }} -net0 {{ net_value }} -ipconfig0 'gw={{ gw_value }},ip={{ item.value.ip_value }}/24' -nameserver '{{ nameservers }}' -searchdomain {{ domain }}
    loop: "{{ lookup('dict', vms) }}"

  - name: add cloudinit user and ssh pub key to VM
    community.general.proxmox_kvm:
      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"
      vmid: "{{ item.value.vm_new_id }}"
      update: yes
      ciuser: root
#      do not use cipassword, use ssh keys instead
#      cipassword: supersecret  
      sshkeys: "{{ ssh_pub }}"      
    loop: "{{ lookup('dict', vms) }}"

  - name: starting VM
    community.general.proxmox_kvm:

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      vmid: "{{ item.value.vm_new_id }}"
      state: started
    loop: "{{ lookup('dict', vms) }}"

#  - name: adding newly created VM to ansible's inventory
#    add_host:
#      name: "{{ vm_new_name }}"
#      hostname: "{{ ip_value }}"

