---

# create vm

- name: create VM on Proxmox host
  hosts: vmpool01
  become: true
  # vars:
  #   local_repo: '/root/ladmex'

  tasks:

  - name: Create a full clone of the templ with id 100
    community.general.proxmox_kvm:
      vmid: 135
      node: "vmpool01"
      api_user: "root@pam"
      api_password: "kesomago"
      # api_token_id: "root@pam!terraform"  
      # api_token_secret: "dfb7917c-3f39-49c5-8428-6cf0d715fb38"
      api_host: "192.168.80.10"
      clone: "ubuntu-2004-cloud-templ"
      full: yes

      name: "test_vm"
      storage: "SSD"
      sockets: 1
      cores: 2
      memory: 2048
      scsi:
        scsi0: "SSD:10G,format:raw"

      ciuser: "root"  
      ide:
        ide2: 'SSD:cloudinit'
      sshkeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+BK8ZYvPaZ0VighkzODkJWpFaGGlcInIiX19xrFU/fH85LZ0B3z79z1lSRdu+cVtV98TakYpMD6rm01N8f0FpKVMOJLTqyx/VaSC2Dse1fo3qISAB5b6jpkKc9GjHBtfHGsG4i/qinakrmKgpt1AhVhX+nYhvNWLMZxVLs9UHnoN2vXtFo9wCGMh7AxMu2oTqi8zk5Fip/DrRvXBN3zBBhVfWMXUta1mTbsquirVZUdTV70vlhg7aabV7aFyN3YASrHJutIl/BC3BaPwoJAAba5YS2WIrMbp3MYcwVHsSBB0EEj39xEgZj2Se3d9Hb9t+zOShdQGVmThsdnnTSkDefmiMIFugYJDX742+Uy7m80CyJ6gm4TlYV0CKl3qqPlvwuRRwUYM8O7BFFuGKVu+sQsRdcrF0kCi+cspQUAzIWcxTfgmDkxqMjRa8GkV95hLJaTuJWBYsr1NEaPCcc2NbhThxfVd9hYIXTw+fLQlP4hJK8hFtp+OSU3WWMP05Y9E= i-tango\andrey_abramenko@DESKTOP-CQLGVSH'
      searchdomains: 'i-tango.ru'
      nameservers:
        - '192.168.82.2'
        - '192.168.82.3'
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: "gw=192.168.82.1,ip=192.168.82.31/24" 


      agent: 1
