---

- name: create VM on Proxmox host
  hosts: vmpool01
  become: true
  gather_facts: no

  vars:
    api_host_name: vmpool01.i-tango.ru
    api_user_name: root@pam
    node_name: vmpool01
    vm_template: ubuntu2004-cloud
    templ_id: 211
#   new VM parameters
    vm_new_id: 138
    vm_new_name: test-ci      # VM name must DO NOT contain '_'
    storage_name: SSD
    sock: 1
    core: 2
    mem: 2048
    disk_size: 6G
    net_value: 'virtio,bridge=vmbr1'
    gw_value: 192.168.82.1
    ip_value: 192.168.82.62
    nameservers: 192.168.82.2 192.168.82.3
    domain: i-tango.ru
    ssh_pub: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+BK8ZYvPaZ0VighkzODkJWpFaGGlcInIiX19xrFU/fH85LZ0B3z79z1lSRdu+cVtV98TakYpMD6rm01N8f0FpKVMOJLTqyx/VaSC2Dse1fo3qISAB5b6jpkKc9GjHBtfHGsG4i/qinakrmKgpt1AhVhX+nYhvNWLMZxVLs9UHnoN2vXtFo9wCGMh7AxMu2oTqi8zk5Fip/DrRvXBN3zBBhVfWMXUta1mTbsquirVZUdTV70vlhg7aabV7aFyN3YASrHJutIl/BC3BaPwoJAAba5YS2WIrMbp3MYcwVHsSBB0EEj39xEgZj2Se3d9Hb9t+zOShdQGVmThsdnnTSkDefmiMIFugYJDX742+Uy7m80CyJ6gm4TlYV0CKl3qqPlvwuRRwUYM8O7BFFuGKVu+sQsRdcrF0kCi+cspQUAzIWcxTfgmDkxqMjRa8GkV95hLJaTuJWBYsr1NEaPCcc2NbhThxfVd9hYIXTw+fLQlP4hJK8hFtp+OSU3WWMP05Y9E= i-tango\andrey_abramenko@DESKTOP-CQLGVSH'

  vars_prompt:
    - name: api_pass
      prompt: Enter password to PVE {{ api_user_name }} account


  tasks:

  - name: create a full clone of the templ with id {{ templ_id }}
    community.general.proxmox_kvm:
      # api_token_id: "root@pam!terraform"
      # api_token_secret: "dfb7917c-3f39-49c5-8428-6cf0d715fb38"

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      clone: "{{ vm_template }}"
      vmid: "{{ templ_id }}"
      full: yes
      newid: "{{ vm_new_id  }}"
      name: "{{ vm_new_name }}"
      storage: "{{ storage_name }}"
      format: raw
#      timeout: 200
#      sshkeys: "{{ ssh_pub }}"

  - name: update VM's cpu/memory to {{ core }}c/{{ sock }}sock/{{ mem }}
    community.general.proxmox_kvm:

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      update: yes

      vmid: "{{ vm_new_id }}"
      sockets: "{{ sock }}"
      cores: "{{ core }}"
      memory: "{{ mem }}"

  - name: setting disk size to {{ disk_size }}
    shell: qm resize {{ vm_new_id  }} scsi0 {{ disk_size }}

  - name: setting network with addr {{ ip_value }}/24
    shell: qm set {{ vm_new_id }} -net0 {{ net_value }} -ipconfig0 'gw={{ gw_value }},ip={{ ip_value }}/24' -nameserver '{{ nameservers }}' -searchdomain {{ domain }}

  - name: add cloudinit user and ssh pub key to VM
    community.general.proxmox_kvm:

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"
      vmid: "{{ vm_new_id }}"
      update: yes
      ciuser: root
#      do not use cipassword, use ssh keys instead
#      cipassword: supersecret  
      sshkeys: "{{ ssh_pub }}"      

  - name: starting VM
    community.general.proxmox_kvm:

      api_host: "{{ api_host_name }}"
      api_user: "{{ api_user_name }}"
      api_password: "{{ api_pass }}"
      node: "{{ node_name }}"

      vmid: "{{ vm_new_id }}"
      state: started

#  - name: adding newly created VM to ansible's inventory
#    add_host:
#      name: "{{ vm_new_name }}"
#      hostname: "{{ ip_value }}"

