---
- name: install wikijs, copy config and configure
  hosts: mediawikis
  become: true
  vars:
    db_server_ip: "{{ hostvars[groups['mysql_master'][0]].inventory_hostname }}"
    nodejs_url: "https://deb.nodesource.com/node_16.x"
    wikijs_gz_url: "https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz"
  tasks:

  - name: add nodejs apt key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: add nodejs ppa for apt repo
    apt_repository:
      repo: deb "{{ nodejs_url }}" focal main
      update_cache: yes

  - name: Install nodejs
    apt:
      update_cache: yes
      name: nodejs
      state: present

  - name: create dir wiki.js
    file:
      path: /var/www/wikijs
      state: directory
  
  - name: download and unpack wiki.js
    unarchive:
      src: "{{ wikijs_gz_url }}"
      dest: /var/www/wikijs
      remote_src: yes

  - name: copying wiki.js config file from repo to /var/www/wikijs
    copy:
      src: /root/ladmex/config.yml
      dest: /var/www/wikijs/

  - name: modifying config.yml mysql host    
    lineinfile:
      dest: /var/www/wikijs/config.yml
      regexp: '^  host:'
      line: '  host: {{ db_server_ip }}'     

  - name: copy systemd file for wikijs
    copy:
      src: files/service
      dest: /etc/systemd/system/wikijs.service
      mode: 644
    register: service_conf

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    when: service_conf.changed


  - name: Start wikijs service
    service:
      name: wikijs
      state: started
      enabled: yes            
