---
- name: copying kibana deb file
  copy:
    src: "{{ repo_path }}/{{ kibana_package }}"
    dest: /root

- name: install a .deb package
  apt:
    deb: /root/{{ kibana_package }}

- name: adding lines in kibana config file
  blockinfile:
    path: /etc/kibana/kibana.yml
    block: |
      server.port: 5601
      server.host: "0.0.0.0"
      elasticsearch.hosts: ["http://localhost:9200"]

- name: start service kibana 
  systemd:
    name: kibana 
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:5601"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
