---
- name: copying kibana deb file
  copy:
    src: "{{ repo_path }}/{{ kibana_package }}"
    dest: /root

- name: install a .deb package
  apt:
    deb: /root/{{ kibana_package }}

- name: start service kibana 
  systemd:
    name: kibana 
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:5601"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
