---
- name: install kibana
  hosts: observer
  become: true
  vars:
    repo_path: "/root"  
    #filebeat_conf_path: "/etc/grafana"
    elastic_package: "kibana-7.17.8-amd64.deb"
    # grafana_datasrc: "grafana_datasrc.yml"
    # grafana_dash_cfg: "grafana_dash.yml"
    # grafana_dash_json: "node-exporter-full_rev29.json"
  
  tasks:
  - name: copying filebeat deb file
    copy:
      src: "{{ repo_path }}/{{ kibana_package }}"
      dest: /root

  - name: install a .deb package
    ansible.builtin.apt:
      deb: /root/{{ kibana_package }}

  - name: start service kibana 
    systemd:
      name: kibana 
      state: started
      enabled: yes

  - name: wait for service up
    uri:
      url: "http://127.0.0.1:5601"
      status_code: 200
    register: __result
    until: __result.status == 200
    retries: 120
    delay: 1
