---

- name: add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs ppa for apt repo
  apt_repository:
    repo: deb "{{ nodejs_url }}" focal main
    update_cache: yes

- name: Install nodejs
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: create dir wiki.js
  file:
    path: "{{ wikijs_path }}"
    state: directory

- name: download and unpack wiki.js
  unarchive:
    src: "{{ wikijs_gz_url }}"
    dest: "{{ wikijs_path }}"
    remote_src: yes

- name: copying wiki.js config file from repo to /var/www/wikijs
  copy:
    src: config.yml
    dest: "{{ wikijs_path }}"

- name: modifying config.yml mysql host    
  lineinfile:
    dest: "{{ wikijs_path }}/config.yml"
    regexp: '^  host:'
    line: '  host: {{ db_server_ip }}'     

- name: copy systemd file for wikijs
  copy:
    src: wikijs.service
    dest: /etc/systemd/system/wikijs.service
    mode: 644
  register: service_conf

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: service_conf.changed


- name: Start wikijs service
  service:
    name: wikijs
    state: started
    enabled: yes            
