---
- name: copying filebeat deb file
  copy:
    src: "{{ repo_path }}/{{ elastic_package }}"
    dest: /root

- name: install a .deb package
  ansible.builtin.apt:
    deb: /root/{{ elastic_package }}

- name: adding java memory restrictions file
  copy:
    dest: /etc/elasticsearch/jvm.options.d/jvm.options
    content: |
      -Xms1g
      -Xmx1g

- name: start service elasticsearch 
  systemd:
    name: elasticsearch 
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:9200"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
